version: 2

models:
  - name: stg_customers
    columns:
      - name: id
        tests:
          - not_null
          - unique
      - name: customer_city
        tests:
          - not_null
      - name: customer_state
        tests:
          - not_null

  - name: stg_sellers
    columns:
      - name: id
        tests:
          - not_null
          - unique
      - name: seller_city
        tests:
          - not_null
      - name: seller_state
        tests:
          - not_null

  - name: stg_orders
    columns:
      - name: id
        tests:
          - not_null
          - unique
      - name: customer_id
        tests:
          - not_null
      - name: status
        tests:
          - not_null
          - accepted_values:
              values: ['delivered', 'shipped', 'canceled', 'processing', 'invoiced', 'unavailable', 'approved', 'created']

  - name: stg_order_items
    columns:
      - name: id
        tests:
          - not_null
      - name: order_id
        tests:
          - not_null
      - name: product_id
        tests:
          - not_null
      - name: seller_id
        tests:
          - not_null
      - name: price
        tests:
          - not_null

  - name: stg_order_payments
    columns:
      - name: order_id
        tests:
          - not_null
      - name: payment_type
        tests:
          - not_null
          - accepted_values:
              values: ['credit_card', 'boleto', 'voucher', 'debit_card', 'not_defined']
      - name: payment_value
        tests:
          - not_null

  - name: stg_products
    columns:
      - name: id
        tests:
          - not_null
          - unique