version: 2

models:
  - name: dim_customers
    columns:
      - name: customer_id
        tests:
          - not_null
          - unique
      - name: city
        tests:
          - not_null
      - name: state
        tests:
          - not_null

  - name: dim_sellers
    columns:
      - name: seller_id
        tests:
          - not_null
          - unique
      - name: city
        tests:
          - not_null
      - name: state
        tests:
          - not_null

  - name: dim_products
    columns:
      - name: product_id
        tests:
          - not_null
          - unique

  - name: dim_date
    columns:
      - name: date_id
        tests:
          - not_null
          - unique
      - name: year
        tests:
          - not_null
      - name: month
        tests:
          - not_null

  - name: fct_orders
    columns:
      - name: order_id
        tests:
          - not_null
          - unique
      - name: customer_id
        tests:
          - not_null
          - relationships:
              to: ref('dim_customers')
              field: customer_id
      - name: date_id
        tests:
          - not_null
          - relationships:
              to: ref('dim_date')
              field: date_id
      - name: total_payment_value
        tests:
          - not_null

  - name: fct_order_items
    columns:
      - name: order_item_id
        tests:
          - not_null
      - name: order_id
        tests:
          - not_null
          - relationships:
              to: ref('fct_orders')
              field: order_id
      - name: product_id
        tests:
          - not_null
          - relationships:
              to: ref('dim_products')
              field: product_id
      - name: seller_id
        tests:
          - not_null
          - relationships:
              to: ref('dim_sellers')
              field: seller_id